apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: {{ .Values.flask.service.type }}
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.service.targetPort }}